name: nova_store
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.3.2

dependencies:
  animate_do: ^3.3.4
  connectivity_plus: ^6.1.1
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  json_serializable: 6.9.0
  lottie: 3.2.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  shared_preferences: ^2.3.4

dev_dependencies:
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.3

  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  retrofit_generator: ^9.1.5
  # json_serializable: ^6.9.2
  very_good_analysis: ^6.0.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/core/splash.png"
  image_path_ios: "assets/images/core/splash.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/core/play_store_512.png"

flutter:
  uses-material-design: true

  assets:
    - .env.production
    - .env.dev
    - assets/jsons/
    - assets/images/admin/
    - assets/images/core/
    - assets/images/customer/
    - assets/lotties/
    - assets/gifs/
    - assets/vector/
    - lang/ar.json
    - lang/en.json

  fonts:
    # English font
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/Poppins-Regular.ttf
        - weight: 400
        - asset: assets/fonts/english/Poppins-Medium.ttf
        - weight: 500
        - asset: assets/fonts/english/Poppins-Bold.ttf
        - weight: 700

    # Arabic font
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/Cairo-Regular.ttf
        - weight: 400
        - asset: assets/fonts/arabic/Cairo-Medium.ttf
        - weight: 500
        - asset: assets/fonts/arabic/Cairo-Bold.ttf
        - weight: 700
